set -gx PIP_DISABLE_PIP_VERSION_CHECK 1
set -gx PIP_REQUIRE_VIRTUALENV 1
set -gx PYTHONDONTWRITEBYTECODE 1
set -gx PYTHONUSERBASE ~/.local
set -gx UV_PREVIEW 1
set -gx UV_PUBLISH_USERNAME __token__
set -gx VIRTUAL_ENV_DISABLE_PROMPT 1
