[[provider]]
provider = "github"
name = "branchv"
path = "."
auth_type = "gh-cli"
auth_http = true
skip_forks = true

[[provider]]
provider = "github"
name = "python-poetry"
path = "."
auth_type = "gh-cli"
auth_http = true
skip_forks = true
exclude = ["crashtest", "poetry-ghsa-", "roadmap", "test-fixture-"]
